### ISSUE TITLE
Count CC of generateSpan() manually

### ISSUE THREAD

**Issue by augustjanse** [augustjanse/opencensus-java#13]
https://github.com/augustjanse/opencensus-java/blob/master/exporters/trace/zipkin/src/main/java/io/opencensus/exporter/trace/zipkin/ZipkinExporterHandler.java#L105

**Comment by txing001** [comment]
<details><summary>Spoilers!</summary>
pi =  5
s =1 
M=5-1+2=6
@augustjanse 
</details>

**Comment by GlennOlsson** [comment]
`M = 8 - 1 + 2`

for loops should be 1 π as they can be written as while
Unsure about nested if, if they all counts as one. As in 
```java
if(s1){
  if(s2){...}
  
  if(s3){...}
}
```
They should probably just be counted as usual, one per statement

**Comment by augustjanse** [comment]
<details><summary>Spoilers!</summary>#13: 8-1+2=9 </details>
