### ISSUE TITLE
Count CC of create() manually

### ISSUE THREAD

**Issue by augustjanse** [augustjanse/opencensus-java#14]
https://github.com/augustjanse/opencensus-java/blob/master/api/src/main/java/io/opencensus/common/Duration.java#L53

**Comment by txing001** [comment]
<details><summary>Spoilers!</summary>
pi =7
s = 6
M = 7-6+1 = 2
@augustjanse 
</details>

**Comment by GlennOlsson** [comment]
`M = 8 - 6 + 2 = 4`

**Comment by augustjanse** [comment]
<details><summary>Spoilers!</summary>#14: 8-6+2=4 </details>
