### ISSUE TITLE
Count CC of equals() manually

### ISSUE THREAD

**Issue by augustjanse** [augustjanse/opencensus-java#15]
https://github.com/augustjanse/opencensus-java/blob/master/api/src/main/java/io/opencensus/tags/TagContext.java#L63

**Comment by txing001** [comment]
<details><summary>Spoilers!</summary>
pi = 8
s = 3
M= 8 -3 +2 =7
@augustjanse 
</details>

**Comment by GlennOlsson** [comment]
`M = 8 - 3 + 2 = 7`

**Comment by augustjanse** [comment]
<details><summary>Spoilers!</summary>#15: 10-3+2=9</details>
