### ISSUE TITLE
Count CC of fromByteArray() manually

### ISSUE THREAD

**Issue by augustjanse** [augustjanse/opencensus-java#16]
https://github.com/augustjanse/opencensus-java/blob/master/impl_core/src/main/java/io/opencensus/implcore/trace/propagation/BinaryFormatImpl.java#L109

**Comment by txing001** [comment]
<details><summary>Spoilers!</summary>
pi=8 s=6 
M=8-6+2=4
@augustjanse 
</details>

**Comment by GlennOlsson** [comment]
π = 8, s = 6, M = π - s + 2 = 8 - 6 + 2 = 4

If we count `checkNotNull(bytes, "bytes");` as an exit point (assume it throws if bytes is null) then the complexity is 3

**Comment by augustjanse** [comment]
<details><summary>Spoilers!</summary>#16: 8-6+2=4 </details>
