### ISSUE TITLE
Compare results to Codecov

### ISSUE THREAD

**Issue by augustjanse** [augustjanse/opencensus-java#17]
```
3. Are the results of your tool consistent with existing coverage tools?
```

**Comment by augustjanse** [comment]
Results of our DIY code coverage compared to this: https://codecov.io/gh/census-instrumentation/opencensus-java/branch/master/

**Comment by augustjanse** [comment]
Part of #5

**Comment by GlennOlsson** [comment]
Are we using Codecov or Jacoco? Thinking as we don't have access to their codecov, right? So we can't compare the improvement

**Comment by augustjanse** [comment]
This is under 3.5.1, i.e. before we begin our improvement. So I interpreted it as comparing their existing tool to our new tool, for the unimproved code

**Comment by augustjanse** [comment]
That's pretty much a guess, though!

**Comment by GlennOlsson** [comment]
Right, sounds fair!

**Comment by augustjanse** [comment]
On the other hand, it looks like the online codecov doesn't have all reports, so it's a good idea running jacoco locally

**Comment by augustjanse** [comment]
Should be done

**Comment by augustjanse** [comment]
Just write a few sentences, should be enough

**Comment by augustjanse** [comment]
@txing001 did something about it
